[package]
name = "Inmate"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
Justice = { path = "../Justice" }
tokio = { version = "1.43.0", features = ["full"]}
serde = "1.0.217"
serde_json = "1.0.135"
